import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <header className="flex flex-col items-center justify-center flex-1 w-full py-5">
          <h1 className="text-2xl md:text-5xl font-bold text-red-800 text-center">
            My Christmas Store
          </h1>
          <h2 className="text-md md:text-2xl font-bold text-red-800 text-center mt-4 mb-2 px-2">
            Find your favorite Christmas products and ask them with a single
            click
          </h2>
          {/* <nav>
            <ul className="flex flex-row space-x-4">
              <li>
                <a href="/">Products</a>
              </li>
              <li>
                <a href="/products">Cart</a>
              </li>
            </ul>
          </nav> */}
        </header>
        {children}
      </body>
    </html>
  );
}
